# Changes here will be overwritten by Copier
AnswerStrategy: minimum
Authors: 'Luiz M. Faria and Nicolas Lebbe'
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Luiz M. Faria and Nicolas Lebbe
PackageName: LevelSetMethods
PackageOwner: maltezfaria
PackageUUID: ca3df947-0575-4ae6-b9a3-78df393a7451
_commit: v0.13.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
