#
# alignement options
align_assignment = true
align_conditional = true
align_matrix = false
align_pair_arrow = true
align_struct_field = true
always_for_in = true
always_use_return = true
annotate_untyped_fields_with_any = false
conditional_to_if = true
for_in_replacement = "in"
format_docstrings = true
ignore = ["docs/*"]
import_to_using = false
indent = 4
indent_submodule = true
join_lines_based_on_source = false
long_to_short_function_def = false
margin = 92
normalize_line_endings = "auto"
pipe_to_function_call = false
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
short_to_long_function_def = true
surround_whereop_typeparameters = true
trailing_comma = true
trailing_zero = true
whitespace_in_kwargs = true
whitespace_ops_in_indices = false
whitespace_typedefs = false
