name = "LevelSetMethods"
uuid = "ca3df947-0575-4ae6-b9a3-78df393a7451"
authors = ["Luiz M. Faria and Nicolas Lebbe"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
MakieExt = "Makie"

[compat]
LinearAlgebra = "1.11.0"
StaticArrays = "1.9.7"
