name = "LevelSetMethods"
uuid = "ca3df947-0575-4ae6-b9a3-78df393a7451"
authors = ["Luiz M. Faria and Nicolas Lebbe"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
MMG_jll = "86086c02-e288-5929-a127-40944b0018b7"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MarchingCubes = "299715c1-40a9-479a-aaf9-4a633d36f717"

[extensions]
MMGSurfaceExt = ["MMG_jll", "MarchingCubes"]
MMGVolumeExt = "MMG_jll"
MakieExt = "Makie"

[compat]
julia = "1.9"
LinearAlgebra = "1"
Makie = "0.21"
MarchingCubes = "0.1.10"
StaticArrays = "1"
MMG_jll = "5"
